### ISSUE TITLE
why

### ISSUE THREAD

**Issue by philipjscott** [marceloneil/youtube-pptx#1]
see above

**Comment by marceloneil** [comment]
I couldn't find any viable solutions, so I built my own :disappointed:

**Comment by ScottyFillups** [comment]
I see

This is engineering at its finest

Godspeed Marcel o/

**Comment by philipjscott** [comment]
I thought this repository was made as a joke; reminded me of this: https://www.youtube.com/watch?v=_3loq22TxSc

Seems like you're using this to tackle a real problem; I hope you overcome whatever problem you're facing :smiley:

**Comment by marceloneil** [comment]
That was a fun video! I converted it to powerpoint but it's 2.6GB and I can't get it to open :/

<sub><sup>also this repo is a joke :^)</sup></sub>
